import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Socify App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <nav>
          <img />
          <label for="email">Email</label>
          <input type="textbox" name='email' className={styles.txtbx}></input>
          <label for="password">Password</label>
          <input type="password" name='password' className={styles.txtbx}></input>  
          <button type="button" className={styles.logbtn}>Login</button>
          
        </nav>
      </header>

      <main className={styles.main}>
        
        
      </main>

      <footer className={styles.footer}>
        <p>
          Designed with <span id={styles.footemp}>love</span> by Pradeep Mondal
        </p>

      </footer>
    </>
  )
}
